blank_issues_enabled: false
contact_links:
  - name: Issues are not accepted
    url: https://github.com/YOUR-USERNAME/YOUR-REPO
    about: This repository does not accept public issues. Please do not submit.
