blank_issues_enabled: false
contact_links:
  - name: Issues are not accepted
    url: https://github.com/HALO-China/HALO-China.github.io
    about: This repository does not accept public issues. Please do not submit.
